[supervisord]
nodaemon=true
user=root

[program:cron]
command=cron -f
autostart=true
autorestart=true[program:external_app]
command=python3 /app/external_app.py
directory=/app
user=www-data
autostart=true
autorestart=true

[program:internal_app]
command=python3 /app/internal_app.py
directory=/app
user=www-data
autostart=true
autorestart=true